# logging function

In [1]:
from datetime import datetime
import ipyparams

def file_name():
    currentNotebook = ipyparams.notebook_name
    split_name = currentNotebook.split(".")
    return str(split_name[0])

def log(prioity,messenage):
    #determine file name
    log_file = file_name() + "_log_file.txt"
    print(log_file)
    #logging function
    datetime_stamp = "%Y-%m-%d %H:%M:%S"
    now_time = datetime.now()
    datetime_log = now_time.strftime(datetime_stamp)
    with open(log_file,'a') as f:
        f.write(datetime_log + ',' + '[' + prioity + ']' + messenage + '\n')

In [26]:
log("action","ready to start query")

practice_load_query_log_file.txt

# objective

* download the csv file, and put into folder
* read csv into dataframe
* create table into database, server choose sqlite3
* input df into sql databasse
* start query

In [12]:
import pandas as pd
import glob

#sql libraray
%load_ext sql
import csv, sqlite3

### read csv into dataframe

In [51]:
def choose_csv_file(index):
    ##choose csv file, naming is too long, prevent key-in failure
    all_csv_file = glob.glob('download/*.csv')
    print(all_csv_file)
    print("list of all csv files:\n",all_csv_file)

    #choose target file
    import_csv_file = all_csv_file[0]
    
    return import_csv_file

In [52]:
choose_csv_file(0)

['download/Chicago_Public_Schools_-_Progress_Report_Cards__2011-2012_.csv']
list of all csv files:
 ['download/Chicago_Public_Schools_-_Progress_Report_Cards__2011-2012_.csv']

'download/Chicago_Public_Schools_-_Progress_Report_Cards__2011-2012_.csv'

In [17]:
df = pd.read_csv(import_csv_file)
df.head()

,School ID,Name of School,"Elementary, Middle, or High School",Street Address,City,State,ZIP Code,Phone Number,Link,Network Manager,...,RCDTS Code,X_COORDINATE,Y_COORDINATE,Latitude,Longitude,Community Area Number,Community Area Name,Ward,Police District,Location
0,609966,Charles G Hammond Elementary School,ES,2819 W 21st Pl,Chicago,IL,60623,(773) 535-4580,http://schoolreports.cps.edu/SchoolProgressRep...,Pilsen-Little Village Elementary Network,...,150000000000000,1157809.015,1889554.623,41.852691,-87.696278,30,SOUTH LAWNDALE,12,10,"(41.85269133, -87.69627777)"
1,610539,Marvin Camras Elementary School,ES,3000 N Mango Ave,Chicago,IL,60634,(773) 534-2960,http://schoolreports.cps.edu/SchoolProgressRep...,Fullerton Elementary Network,...,150000000000000,1137482.296,1919394.900,41.934966,-87.770165,19,BELMONT CRAGIN,30,25,"(41.93496641, -87.77016525)"
2,609852,Eliza Chappell Elementary School,ES,2135 W Foster Ave,Chicago,IL,60625,(773) 534-2390,http://schoolreports.cps.edu/SchoolProgressRep...,Ravenswood-Ridge Elementary Network,...,150000000000000,1161016.902,1934466.545,41.975867,-87.683254,4,LINCOLN SQUARE,47,20,"(41.975867, -87.68325438)"
3,609835,Daniel R Cameron Elementary School,ES,1234 N Monticello Ave,Chicago,IL,60651,(773) 534-4290,http://schoolreports.cps.edu/SchoolProgressRep...,Garfield-Humboldt Elementary Network,...,150000000000000,1151767.546,1908130.068,41.903785,-87.717963,23,HUMBOLDT PARK,26,25,"(41.90378521, -87.71796315)"
4,610521,Sir Miles Davis Magnet Elementary Academy,ES,6730 S Paulina St,Chicago,IL,60636,(773) 535-9120,http://schoolreports.cps.edu/SchoolProgressRep...,Englewood-Gresham Elementary Network,...,150000000000000,1166133.893,1859929.018,41.771222,-87.666567,67,WEST ENGLEWOOD,15,7,"(41.77122181, -87.66656657)"

### create table into database, server choose sqlite3

In [23]:
##build db and connect to db
#prevent key-in failure, make variable for db name
db_name = "RealWorldData.db"

#sqlite3 connection
con = sqlite3.connect(db_name)
cur = con.cursor()

#magic connection
%sql sqlite:///{db_name}

### input df into sql databasse

In [19]:
#input
#prevention, aliasing table name
table_name = "chicago_public_schools"
df.to_sql(table_name, con, if_exists='replace',index=False, method='multi')

/Users/jianlin/opt/anaconda3/lib/python3.8/site-packages/pandas/core/generic.py:2605: UserWarning: The spaces in these column names will not be changed. In pandas versions < 0.14, spaces were converted to underscores.
  sql.to_sql(

In [21]:
##check table exists
#magic method
%sql SELECT name FROM sqlite_schema WHERE type='table';

 * sqlite:///RealWorldData.db
Done.

[('chicago_public_schools',)]

In [24]:
#sqlite3 method
result = cur.execute(""" SELECT name FROM sqlite_master WHERE type='table';""")
print(result.fetchall())

[('chicago_public_schools',)]

### start query

In [53]:
table_name

'chicago_public_schools'

In [58]:
%%sql
select *
from {table_name}
limit 5;

 * sqlite:///RealWorldData.db
Done.

[(609966, 'Charles G Hammond Elementary School', 'ES', '2819 W 21st Pl ', 'Chicago', 'IL', 60623, '(773) 535-4580', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_609966.pdf', 'Pilsen-Little Village Elementary Network', 'WEST SIDE COLLABORATIVE', 'No', 'Track_E', 'Not on Probation', 'Level 2', 'No', 'Average', 40.0, 'NDA', 'NDA', 'Average', 41.0, 'Average', 43.0, 'NDA', 'NDA', 'NDA', 'NDA', 'Weak', '43', 'Weak', '45', 95.3, 8.5, 95.2, 92.0, '77.4', 'NDA', '27.4', '24.8', '62.4', '53.7', '38.1', '28.8', '60.2', '59.8', '12.8', '5.3', 10.1, 5.8, 0.5, 0.2, 'Yellow', 'Yellow', '25', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 446, 39, 'NDA', 150000000000000, 1157809.015, 1889554.6230000001, 41.85269133, -87.69627777, 30, 'SOUTH LAWNDALE', 12, 10, '(41.85269133, -87.69627777)'),
 (610539, 'Marvin Camras Elementary School', 'ES', '3000 N Mango Ave ', 'Chicago', 'IL', 60634, '(773) 534-2960', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610539.pdf', 'Fullerton Elementary Network', 'NORTH-NORTHWEST SIDE COLLABORATIVE', 'No', 'Standard', 'Not on Probation', 'Not Enough Data', 'No', 'Average', 54.0, 'Average', '58', 'Weak', 37.0, 'Average', 41.0, 'Very Strong', '83', 'Very Strong', '88', 'Average', '51', 'Strong', '55', 95.1, 4.3, 0.0, 97.7, '47.5', '39.9', '30.8', '27.8', '47.8', '38.6', '41.1', '38.5', '49.2', '55.4', '15.3', '30.5', 11.2, 12.0, -1.8, -0.3, 'Red', 'Yellow', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 826, 30, 'NDA', 150000000000000, 1137482.2959999999, 1919394.9, 41.93496641, -87.77016525, 19, 'BELMONT CRAGIN', 30, 25, '(41.93496641, -87.77016525)'),
 (609852, 'Eliza Chappell Elementary School', 'ES', '2135 W Foster Ave ', 'Chicago', 'IL', 60625, '(773) 534-2390', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_609852.pdf', 'Ravenswood-Ridge Elementary Network', 'NORTH-NORTHWEST SIDE COLLABORATIVE', 'Yes', 'Standard', 'Not on Probation', 'Level 1', 'No', 'Strong', 70.0, 'Strong', '65', 'Average', 53.0, 'Average', 51.0, 'Average', '56', 'Average', '48', 'Average', '50', 'Average', '52', 95.1, 2.9, 96.7, 98.9, '72.6', '57', '56', '54.4', '55.2', '69', '53.2', '63.9', '60', '59.8', '12.8', '41', 19.6, 17.6, 0.4, 1.0, 'Yellow', 'Green', '27.5', '63.6', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 451, 31, 'NDA', 150000000000000, 1161016.902, 1934466.545, 41.975867, -87.68325438, 4, 'LINCOLN SQUARE', 47, 20, '(41.975867, -87.68325438)'),
 (609835, 'Daniel R Cameron Elementary School', 'ES', '1234 N Monticello Ave ', 'Chicago', 'IL', 60651, '(773) 534-4290', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_609835.pdf', 'Garfield-Humboldt Elementary Network', 'WEST SIDE COLLABORATIVE', 'No', 'Track_E', 'Probation', 'Level 3', 'No', 'Average', 42.0, 'NDA', 'NDA', 'Average', 49.0, 'Average', 50.0, 'NDA', 'NDA', 'NDA', 'NDA', 'Weak', '46', 'Weak', '46', 92.6, 153.9, 96.2, 98.4, '47.8', '21.1', '16.4', '16.1', '31.3', '34.7', '19.2', '15.6', '33.5', '35', '9.2', '7.1', 10.3, 5.9, -1.0, -1.4, 'Red', 'Red', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 828, 34, 'NDA', 150000000000000, 1151767.5459999999, 1908130.0680000002, 41.90378521, -87.71796315, 23, 'HUMBOLDT PARK', 26, 25, '(41.90378521, -87.71796315)'),
 (610521, 'Sir Miles Davis Magnet Elementary Academy', 'ES', '6730 S Paulina St ', 'Chicago', 'IL', 60636, '(773) 535-9120', 'http://schoolreports.cps.edu/SchoolProgressReport_Eng/Spring2011Eng_610521.pdf', 'Englewood-Gresham Elementary Network', 'SOUTHWEST SIDE COLLABORATIVE', 'No', 'Track_E', 'Probation', 'Level 3', 'No', 'Weak', 35.0, 'NDA', 'NDA', 'Average', 51.0, 'Average', 54.0, 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 93.0, 57.8, 94.5, 100.0, '63.9', '62.3', '24.8', '14.1', '43.1', '52', '22.6', '17.1', '49.1', '45.5', '4.4', '13.3', 5.9, 3.2, 0.0, -0.9, 'Yellow', 'Red', '25.5', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 'NDA', 354, 43, 'NDA', 150000000000000, 1166133.893, 1859929.0180000002, 41.77122181, -87.66656657, 67, 'WEST ENGLEWOOD', 15, 7, '(41.77122181, -87.66656657)')]

#1. How many Elementary Schools are in the dataset?

In [59]:
%%sql
    select distinct(school_type)
    from {table_name}

 * sqlite:///RealWorldData.db
Done.

[('ES',), ('HS',), ('MS',)]

In [60]:
%%sql
    select count(*) AS count_of_school
    from {table_name}
    where school_type = 'ES'

 * sqlite:///RealWorldData.db
Done.

[(462,)]

#2. What is the highest Safety Score?

In [63]:
%%sql
    select "safety score"
    from {table_name}
    order by "safety score" desc
    limit 5;

 * sqlite:///RealWorldData.db
Done.

[(99.0,), (99.0,), (99.0,), (99.0,), (99.0,)]

#3. Which schools have highest Safety Score?

In [65]:
%%sql
    select "name of school","safety score"
    from {table_name}
    where "safety score" =
        (select max("safety score")
        from {table_name})

 * sqlite:///RealWorldData.db
Done.

[('Abraham Lincoln Elementary School', 99.0),
 ('Northside College Preparatory High School', 99.0),
 ('Alexander Graham Bell Elementary School', 99.0),
 ('Oriole Park Elementary School', 99.0),
 ('Mary E Courtenay Elementary Language Arts Center', 99.0),
 ('Ellen Mitchell Elementary School', 99.0),
 ('Stephen Decatur Classical Elementary School', 99.0),
 ('James E McDade Elementary Classical School', 99.0),
 ('Norwood Park Elementary School', 99.0),
 ('Edgar Allan Poe Elementary Classical School', 99.0),
 ('Annie Keller Elementary Gifted Magnet School', 99.0),
 ('James G Blaine Elementary School', 99.0),
 ('Augustus H Burley Elementary School', 99.0),
 ('Talman Elementary School', 99.0),
 ('Edgebrook Elementary School', 99.0),
 ('Northside Learning Center High School', 99.0),
 ('LaSalle Elementary Language Academy', 99.0),
 ('Sauganash Elementary School', 99.0),
 ('Wildwood Elementary School', 99.0)]

#4. What are the top 10 schools with the highest "Average Student Attendance"?

In [71]:
#find the key column
possible_columns = [col for col in df.columns if 'student' in col or 'Attendance' in col]
possible_columns

['Average Student Attendance',
 'Rate of Misconducts (per 100 students) ',
 'Average Teacher Attendance',
 'College Enrollment (number of students) ']

In [74]:
%%sql
    select "Name of School","Average Student Attendance"
    from {table_name}
    order by "Average Student Attendance" desc
    limit 10;

 * sqlite:///RealWorldData.db
Done.

[('John Charles Haines Elementary School', 98.4),
 ('James Ward Elementary School', 97.8),
 ('Rachel Carson Elementary School', 97.6),
 ('Edgar Allan Poe Elementary Classical School', 97.6),
 ('Orozco Fine Arts & Sciences Elementary School', 97.6),
 ('Annie Keller Elementary Gifted Magnet School', 97.5),
 ('Lenart Elementary Regional Gifted Center', 97.4),
 ('Andrew Jackson Elementary Language Academy', 97.4),
 ('Disney II Magnet School', 97.3),
 ('John H Vanderpoel Elementary Magnet School', 97.2)]

#5. Retrieve the list of 5 Schools with the lowest Average Student Attendance sorted in ascending order based on attendance

In [75]:
%%sql
    select "Name of School","Average Student Attendance"
    from {table_name}
    order by "Average Student Attendance" asc
    limit 5;

 * sqlite:///RealWorldData.db
Done.

[('Velma F Thomas Early Childhood Center', None),
 ('Richard T Crane Technical Preparatory High School', 57.9),
 ('Barbara Vick Early Childhood & Family Center', 60.9),
 ('Dyett High School', 62.5),
 ('Wendell Phillips Academy High School', 63.0)]

#6. Now remove the '%' sign from the above result set for Average Student Attendance column

#7. Which Schools have Average Student Attendance lower than 70%?

In [76]:
%%sql
    select "Name of School","Average Student Attendance"
    from {table_name}
    where "Average Student Attendance" < 70.0
    order by "Average Student Attendance" asc

 * sqlite:///RealWorldData.db
Done.

[('Richard T Crane Technical Preparatory High School', 57.9),
 ('Barbara Vick Early Childhood & Family Center', 60.9),
 ('Dyett High School', 62.5),
 ('Wendell Phillips Academy High School', 63.0),
 ('Orr Academy High School', 66.3),
 ('Manley Career Academy High School', 66.8),
 ('Chicago Vocational Career Academy High School', 68.8),
 ('Roberto Clemente Community Academy High School', 69.6)]

#8. Get the total College Enrollment for each Community Area

In [77]:
#find the key column
possible_columns_8 = [col for col in df.columns if 'Enrollment' in col or 'Area' in col]
possible_columns_8

['College Enrollment Rate %',
 'College Enrollment (number of students) ',
 'Community Area Number',
 'Community Area Name']

In [81]:
%%sql
    select
        "Community Area Name",
        SUM("College Enrollment (number of students) ") AS total_enr
    from {table_name}
    group by "Community Area Name"
    Order by total_enr desc

 * sqlite:///RealWorldData.db
Done.

[('SOUTH LAWNDALE', 14793),
 ('BELMONT CRAGIN', 14386),
 ('AUSTIN', 10933),
 ('GAGE PARK', 9915),
 ('BRIGHTON PARK', 9647),
 ('WEST TOWN', 9429),
 ('HUMBOLDT PARK', 8620),
 ('WEST RIDGE', 8197),
 ('NEAR WEST SIDE', 7975),
 ('NEW CITY', 7922),
 ('IRVING PARK', 7764),
 ('NORTH CENTER', 7541),
 ('LOGAN SQUARE', 7351),
 ('LOWER WEST SIDE', 7257),
 ('CHICAGO LAWN', 7086),
 ('LAKE VIEW', 7055),
 ('ROSELAND', 7020),
 ('PORTAGE PARK', 6954),
 ('ALBANY PARK', 6864),
 ('ENGLEWOOD', 6832),
 ('ASHBURN', 6483),
 ('NORWOOD PARK', 6469),
 ('WEST ENGLEWOOD', 5946),
 ('LINCOLN PARK', 5615),
 ('EAST GARFIELD PARK', 5337),
 ('EAST SIDE', 5305),
 ('NORTH LAWNDALE', 5146),
 ('CHATHAM', 5042),
 ('ARCHER HEIGHTS', 4823),
 ('DOUGLAS', 4670),
 ('EDGEWATER', 4600),
 ('DUNNING', 4568),
 ('GARFIELD RIDGE', 4552),
 ('SOUTH SHORE', 4543),
 ('UPTOWN', 4388),
 ('KENWOOD', 4287),
 ('NORTH PARK', 4210),
 ('WEST LAWN', 4207),
 ('WOODLAWN', 4206),
 ('AUBURN GRESHAM', 4175),
 ('LINCOLN SQUARE', 4132),
 ('ROGERS PARK', 4068),
 ('GREATER GRAND CROSSING', 4051),
 ('SOUTH CHICAGO', 4043),
 ('WASHINGTON HEIGHTS', 4006),
 ('HERMOSA', 3975),
 ('WEST ELSDON', 3700),
 ('AVONDALE', 3640),
 ('NEAR NORTH SIDE', 3362),
 ('MORGAN PARK', 3271),
 ('WEST PULLMAN', 3240),
 ('BRIDGEPORT', 3167),
 ('GRAND BOULEVARD', 2809),
 ('WASHINGTON PARK', 2648),
 ('WEST GARFIELD PARK', 2622),
 ('MOUNT GREENWOOD', 2091),
 ('CLEARING', 2085),
 ('HYDE PARK', 1930),
 ('SOUTH DEERING', 1859),
 ('JEFFERSON PARK', 1755),
 ('BEVERLY', 1636),
 ('PULLMAN', 1620),
 ('CALUMET HEIGHTS', 1568),
 ('MCKINLEY PARK', 1552),
 ('RIVERDALE', 1547),
 ('AVALON PARK', 1522),
 ('ARMOUR SQUARE', 1458),
 ('FOREST GLEN', 1431),
 ('NEAR SOUTH SIDE', 1378),
 ('MONTCLARE', 1317),
 ('HEGEWISCH', 963),
 ('EDISON PARK', 910),
 ('LOOP', 871),
 ('OHARE', 786),
 ('BURNSIDE', 549),
 ('FULLER PARK', 531),
 ('OAKLAND', 140)]

#9. Get the 5 Community Areas with the least total College Enrollment sorted in ascending order

In [82]:
%%sql
    select
        "Community Area Name",
        SUM("College Enrollment (number of students) ") AS total_enr
    from {table_name}
    group by "Community Area Name"
    Order by total_enr asc
    limit 5;

 * sqlite:///RealWorldData.db
Done.

[('OAKLAND', 140),
 ('FULLER PARK', 531),
 ('BURNSIDE', 549),
 ('OHARE', 786),
 ('LOOP', 871)]

#10. List 5 schools with lowest safety score.

In [83]:
#find the key column
possible_columns_10 = [col for col in df.columns if 'Name' in col or 'Safety' in col]
possible_columns_10

['Name of School',
 'Collaborative Name',
 'Safety Icon ',
 'Safety Score',
 'Community Area Name']

In [85]:
%%sql
    select 
        "Name of School",
        "Safety Score"
    from {table_name}
    where "Safety Score" not null
    order by "Safety Score" ASC
    limit 5;

 * sqlite:///RealWorldData.db
Done.

[('Edmond Burke Elementary School', 1.0),
 ("Luke O'Toole Elementary School", 5.0),
 ('George W Tilton Elementary School', 6.0),
 ('Foster Park Elementary School', 11.0),
 ('John Fiske Elementary School', 13.0)]

#11. Get the hardship index for the community area which has College Enrollment of 4368

In [87]:
#find the key column
possible_columns_11 = [col for col in df.columns if 'Hardship' in col or 'Area' in col or 'Enrollment' in col]
possible_columns_11

['College Enrollment Rate %',
 'College Enrollment (number of students) ',
 'Community Area Number',
 'Community Area Name']

In [88]:
%%sql
    select "hardship_index"
    from {table_name}

 * sqlite:///RealWorldData.db
Done.

[('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',),
 ('hardship_index',)]

#12. Get the hardship index for the community area which has the highest value for College Enrollment

In [89]:
con.close()

# data clean process
    # column name
    # missing value
    # duplicate check